extends Spatial;

func _ready():
	$music.play();#37
	get_node("scientist/AnimationPlayer").play("default");
	$animation.play("1");
	yield(get_tree().create_timer(17.5), "timeout");
	$animation.play("2");
	$animation.playback_speed = 1.5;
	yield(get_tree().create_timer(5), "timeout");
	get_node("shelter/scientist/AnimationPlayer").play("default");
	$animation.play("3");
	$animation.playback_speed = 1;
	yield(get_tree().create_timer(4.25), "timeout");
	get_node("scientist/AnimationPlayer").play("default");
	get_node("lady_1").visible = true;
	get_node("lady_1/AnimationPlayer").play("default");
	get_node("lady_1/AnimationPlayer").playback_speed = 0.625;
	yield(get_tree().create_timer(0.25), "timeout");
	get_node("shelter").queue_free();
	get_node("player_1").visible = true;
	get_node("player_1/AnimationPlayer").play("default");
	$animation.play("4");
	yield(get_tree().create_timer(2.5), "timeout");
	get_node("player_1").visible = false;
	get_node("player_2").visible = true;
	get_node("player_2/AnimationPlayer").play("default");
	get_node("vehicle_2").visible = true;
	get_node("vehicle_3").visible = true;
	$animation.play("5");
	yield(get_tree().create_timer(7.5), "timeout");
	$animation.play("6");
	yield(get_tree().create_timer(2.25), "timeout");
	get_node("vehicle_3/sound").play();
	yield(get_tree().create_timer(1.75), "timeout");
	get_node("scientist").visible = false;
	get_node("lady_1").visible = false;
	$animation.play("7");
	yield(get_tree().create_timer(2), "timeout");
	$animation.play("8");
	yield(get_tree().create_timer(5), "timeout");
	get_node("specnaz_1/sound").play();
	yield(get_tree().create_timer(2.5), "timeout");
	get_node("specnaz_1").visible = true;
	get_node("specnaz_2").visible = true;
	get_node("specnaz_3").visible = true;
	get_node("specnaz_1/AnimationPlayer").play("default");
	get_node("specnaz_2/AnimationPlayer").play("default");
	get_node("specnaz_3/AnimationPlayer").play("default");
	$animation.play("9");
	yield(get_tree().create_timer(1.25), "timeout");
	get_node("player_3/AnimationPlayer").play("default");
	yield(get_tree().create_timer(0.25), "timeout");
	get_node("player_2").visible = false;
	get_node("player_3").visible = true;
	yield(get_tree().create_timer(0.5), "timeout");
	$animation.play("10");
	yield(get_tree().create_timer(6), "timeout");
	$blast.play();
	get_node("road").queue_free();
	#get_node("vehicle_1").queue_free();
	get_node("vehicle_2").queue_free();
	get_node("vehicle_3").queue_free();
	get_node("specnaz_1").queue_free();
	get_node("specnaz_2").queue_free();
	get_node("specnaz_3").queue_free();
	yield(get_tree().create_timer(10.5), "timeout");
	get_node("lady_2/AnimationPlayer").get_animation("default").loop = true;
	get_node("lady_2/AnimationPlayer").play("default");
	yield(get_tree().create_timer(.5), "timeout");
	get_node("lady_2").visible = true;
	yield(get_tree().create_timer(2), "timeout");
	var _title = get_node("title");
	_title.say("Где я?", 2);
	yield(get_tree().create_timer(1.5), "timeout");
	get_node("final").play();
	yield(get_tree().create_timer(5), "timeout");
	_title.say("Я умер?", 2);
	yield(get_tree().create_timer(43.5), "timeout");
	_title.say("Знаешь, я переехал в Берлин в 81-ом году и все эти годы пролетели одним мгновением.", 6);
	yield(get_tree().create_timer(6), "timeout");
	_title.say("Я был счастлив быть частью этого безумного круговорота борьбы политических полюсов и их развед служб.", 7);
	yield(get_tree().create_timer(7), "timeout");
	_title.say("И кислотные тусовки я обожал.", 2.5);
	yield(get_tree().create_timer(2.5), "timeout");
	_title.say("Через пару месяцев наступят 90-ые и кто знает, что могло бы меня в них ждать.", 6);
	yield(get_tree().create_timer(6), "timeout");
	_title.say("Но находясь в 1989 году я точно могу сказать: Берлин - моя любовь!", 5.5);
